"""Tool: List IAM Access Analyzer findings from Security Hub.

Queries Security Hub for findings generated by IAM Access Analyzer,
with filtering by severity, resource type, status, and free-text search.
Returns paginated results with summary statistics.
"""

import json
import logging
from collections import defaultdict

import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)

securityhub_client = boto3.client("securityhub")


def handler(event, context=None):
    """Query Security Hub for IAM Access Analyzer findings.

    Args:
        event: {
            severity: str - CRITICAL, HIGH, MEDIUM, LOW, INFORMATIONAL (optional)
            resource_type: str - IAMRole, IAMUser, IAMPolicy, S3Bucket, KMSKey, etc. (optional)
            status: str - ACTIVE, ARCHIVED, RESOLVED (default: ACTIVE)
            limit: int - max findings to return (default: 20, max: 100)
            search_text: str - free-text search across title/description (optional)
            next_token: str - pagination token from previous call (optional)
        }

    Returns:
        {
            findings: [...],
            total_count: int,
            summary: {severity_breakdown, resource_type_breakdown, top_recommendations},
            next_token: str or null,
            filters_applied: {...}
        }
    """
    severity = event.get("severity")
    resource_type = event.get("resource_type")
    status = event.get("status", "ACTIVE")
    limit = min(event.get("limit", 10), 50)
    search_text = event.get("search_text")
    next_token = event.get("next_token")

    # Build Security Hub filters
    filters = {
        "ProductName": [{"Value": "IAM Access Analyzer", "Comparison": "EQUALS"}],
        "RecordState": [{"Value": "ACTIVE", "Comparison": "EQUALS"}],
    }

    if severity:
        filters["SeverityLabel"] = [{"Value": severity.upper(), "Comparison": "EQUALS"}]

    if resource_type:
        # Map user-friendly names to Security Hub resource type format
        resource_type_map = {
            "IAMRole": "AwsIamRole",
            "IAMUser": "AwsIamUser",
            "IAMPolicy": "AwsIamPolicy",
            "S3Bucket": "AwsS3Bucket",
            "KMSKey": "AwsKmsKey",
            "LambdaFunction": "AwsLambdaFunction",
            "SQSQueue": "AwsSqsQueue",
            "SecretsManager": "AwsSecretsManagerSecret",
        }
        mapped_type = resource_type_map.get(resource_type, resource_type)
        filters["ResourceType"] = [{"Value": mapped_type, "Comparison": "EQUALS"}]

    if status:
        status_map = {
            "ACTIVE": "NEW",
            "ARCHIVED": "SUPPRESSED",
            "RESOLVED": "RESOLVED",
        }
        workflow_status = status_map.get(status.upper(), status.upper())
        filters["WorkflowStatus"] = [{"Value": workflow_status, "Comparison": "EQUALS"}]

    if search_text:
        filters["Title"] = [{"Value": search_text, "Comparison": "CONTAINS"}]

    try:
        # Build API call params
        api_params = {
            "Filters": filters,
            "MaxResults": limit,
            "SortCriteria": [
                {"Field": "SeverityNormalized", "SortOrder": "desc"},
            ],
        }
        if next_token:
            api_params["NextToken"] = next_token

        response = securityhub_client.get_findings(**api_params)

        # Process findings
        findings = []
        severity_breakdown = defaultdict(int)
        resource_type_breakdown = defaultdict(int)
        recommendations = []

        for finding in response.get("Findings", []):
            sev = finding.get("Severity", {}).get("Label", "UNKNOWN")
            severity_breakdown[sev] += 1

            resources = finding.get("Resources", [{}])
            primary_resource = resources[0] if resources else {}
            res_type = primary_resource.get("Type", "Unknown")
            resource_type_breakdown[res_type] += 1

            # Extract recommendation
            remediation = finding.get("Remediation", {})
            recommendation_text = remediation.get("Recommendation", {}).get("Text", "")
            recommendation_url = remediation.get("Recommendation", {}).get("Url", "")

            if recommendation_text and recommendation_text not in recommendations:
                recommendations.append(recommendation_text)

            # Extract Access Analyzer specific details
            product_fields = finding.get("ProductFields", {})
            finding_type = product_fields.get("type", "")

            processed_finding = {
                "id": finding.get("Id", ""),
                "title": finding.get("Title", ""),
                "description": finding.get("Description", ""),
                "severity": sev,
                "severity_normalized": finding.get("Severity", {}).get("Normalized", 0),
                "resource_type": res_type,
                "resource_id": primary_resource.get("Id", ""),
                "resource_region": primary_resource.get("Region", ""),
                "status": finding.get("Workflow", {}).get("Status", ""),
                "finding_type": finding_type,
                "created_at": finding.get("CreatedAt", ""),
                "updated_at": finding.get("UpdatedAt", ""),
                "recommendation": recommendation_text,
                "recommendation_url": recommendation_url,
                "account_id": finding.get("AwsAccountId", ""),
            }
            findings.append(processed_finding)

        # Build summary
        summary = {
            "severity_breakdown": dict(severity_breakdown),
            "resource_type_breakdown": dict(resource_type_breakdown),
            "top_recommendations": recommendations[:5],
            "highest_severity": _get_highest_severity(severity_breakdown),
        }

        result = {
            "findings": findings,
            "total_count": len(findings),
            "summary": summary,
            "filters_applied": {
                "severity": severity,
                "resource_type": resource_type,
                "status": status,
                "search_text": search_text,
            },
        }

        # Include pagination token if more results exist
        if "NextToken" in response:
            result["next_token"] = response["NextToken"]
            result["has_more"] = True
        else:
            result["has_more"] = False

        return result

    except securityhub_client.exceptions.InvalidAccessException as e:
        logger.error(f"Security Hub access error: {e}")
        return {
            "error": "Security Hub is not enabled or you don't have access. "
            "Please enable Security Hub with IAM Access Analyzer integration.",
            "findings": [],
            "total_count": 0,
        }
    except securityhub_client.exceptions.InvalidInputException as e:
        logger.error(f"Invalid filter input: {e}")
        return {
            "error": f"Invalid filter parameters: {e}",
            "findings": [],
            "total_count": 0,
        }
    except Exception as e:
        logger.error(f"Error querying Security Hub: {e}", exc_info=True)
        return {"error": str(e), "findings": [], "total_count": 0}


def _get_highest_severity(breakdown: dict) -> str:
    """Return the highest severity level found."""
    severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"]
    for sev in severity_order:
        if breakdown.get(sev, 0) > 0:
            return sev
    return "NONE"
